### ISSUE TITLE
over 100% CPU 

### ISSUE THREAD

**Issue by fokkerone** [jedwards1211/meteor-webpack-react#13]
This is what happened when i start your neat lil app on a MBP Retina 

<img width="704" alt="bildschirmfoto 2015-08-11 um 21 59 53" src="https://cloud.githubusercontent.com/assets/96452/9208998/8f60d486-4074-11e5-93cf-c1ce964d63d1.png">

**Comment by fokkerone** [comment]
running the pure meteor todo demo the node process usage is ~.2 %

**Comment by AdamBrodzinski** [comment]
That's odd. Def. shouldn't be that high.

On my 2012 MBP Retina i'm getting 0.1% - 0.2%. Did you happen to add any additional packages or NPM modules?

Here's my stats:

<img width="753" alt="screen shot 2015-08-11 at 6 24 54 pm" src="https://cloud.githubusercontent.com/assets/1445367/9212422/b590f41a-4056-11e5-9a26-fc1ba8c013e4.png">


If you reboot your machine does it help any?

**Comment by jedwards1211** [comment]
@fokkerone I haven't seen anything like that either, would you mind doing a CPU profile of it in Chrome and attaching a screencap of that?

**Comment by fokkerone** [comment]
sure! BTW. have you seen this https://www.youtube.com/watch?v=NBp72NFzHL0
Don´t know if will work with react / react hot reloader

**Comment by AdamBrodzinski** [comment]
Regarding the CSS, it will hot load style changes on save and then only patches the file that changed. Splitting CSS/style files helps speedup a lot too.

This seems faster than the current css loader but i'm comparing a large project with a tiny on at the moment (~2 sec to reload styles)

Thanks for the extra info! Did you get a chance to reboot and try again? I've had some node specific issues that pegged my resources until I rebooted.

**Comment by fokkerone** [comment]
the video title is "CSS injection", but he shows that all frontend editing (Blaze/HTML/CSS/LESS/SCSS.. REACT?) doesn´t require an app restart anymore. 
No reboot, but i have updated node(nvm), npm and meteor to several releases. 
No changes. i will reboot. and try it on a mac mini

**Comment by AdamBrodzinski** [comment]
Ooo I didn't watch the middle :laughing: I'm not sure how they're doing that but one of the big pros of Webpacks 'hot-loading' is that it does the same thing, as opposed to Meteor's 'live-reload' style where the entire page refreshes. It basically patches the module that changed... so the more split up your app is the finer grained changes (from what I understand, perhaps it's even per module function with react-hot-load?). The cool thing is if you have style overrides in Chrome, a reload retains those so they don't get lost.

The [react-hot-loader](https://github.com/gaearon/react-hot-loader) plugin provides even more support for React specifically. Checkout this first video for a few second example and the 2nd video explains how it works:

https://www.youtube.com/watch?v=pw4fKkyPPg8 
https://www.youtube.com/watch?v=ulKrG1me-Ss

Making the  differences more clear  between Meteor's reloading and Webpack is on my todo list! (as well as a quick video screencast)

**Comment by fokkerone** [comment]
So zerlegt, complete different mbp (Node 0.12.7 Meteor 1.1.0.3) same behavoir 106%

**Comment by jedwards1211** [comment]
Ach entschuldigung @fokkerone, I thought it was the browser pegging the CPU, if I had read more carefully I would have seen that it was node pegging the CPU.

I added a dev-debug script that will launch with Meteor in debug mode.  If you pull the latest version and then do the following, you can profile Meteor server-side:
```
> npm install -g node-inspector
```
(if you don't already have node-inspector installed)
```
> cd webpack
> npm run dev-debug
```
And then go to `http://127.0.0.1:8080/debug?port=5858` in your browser.

**Comment by jedwards1211** [comment]
@AdamBrodzinski how fast does Webpack hot loading work for you if you make a JS change?  On some of my other projects it's not much better than refreshing the page, and I'm wondering if I'm doing something wrong.

**Comment by AdamBrodzinski** [comment]
@jedwards1211 for me it's about 2 seconds on the dot. I still want to add a bunch of file to see if it will maintain but from what Pete Hunt was mentioning even large projects (instagram I believe) are around that time. Currently one of my Meteor apps takes 10-15 seconds (no joke) to refresh on save.

However in Dan's video his reloading is only taking < 1 second. His older video was around 2 seconds... not sure if something has changed. https://www.youtube.com/watch?v=xsSnOQynTHs

Also worth mentioning, you can debug the Meteor app specifically by running `meteor debug` instead of `meteor` this will spit out a node-inspector url that you can open up. Now that I think of it, i'll add a target/script for `npm run debug` as well.

I'm not sure what node instance is causing the spike... webpack is running an express server and then there's the core meteor server running... i'm assuming it's the webpack one.

**Comment by jedwards1211** [comment]
@AdamBrodzinski I tried using `meteor debug` but for some reason the node-inspector didn't have a Profiler tab when I did that.  When I used `export NODE_OPTIONS='--debug=5858' &&` before `meteor &`, as someone recommended in a SO post before `meteor debug` existed, I got a node-inspector with a Profiler tab.  It complained about the node version being a bit old to work with it but it profiled nonetheless.  I don't know much about all this, do you have much experience with it?

**Comment by jedwards1211** [comment]
(and the `export NODE_OPTIONS`... is what I put into the `dev-debug.sh` script that's now pushed)

**Comment by AdamBrodzinski** [comment]
> I don't know much about all this, do you have much experience with it?

I haven't used the vanilla node-inspector in a while but the built in one for Meteor is crusty as hell.... not sure what version it is. I also haven't done much with serverside profiling.... only on the clientside. 

> (and the export NODE_OPTIONS... is what I put into the dev-debug.sh script that's now pushed)

Awesome! :+1:

**Comment by fokkerone** [comment]
node-inspector doesn´t run.. i use meteor debug + meteor shell for serverside

**Comment by fokkerone** [comment]
Aha, when i modify the shell script for dev to 

#!/bin/sh
(
  webpack-dev-server --config webpack.config.client.dev.js --progress --colors &
  webpack --config webpack.config.server.js --progress --colors --watch &
  cd ../meteor &&
  ([ ! -d prod ] || mv prod .prod) &&
  ([ ! -d .dev ] || mv .dev dev  )

) | cat

and then start meteor from a second terminal, my CPU activity looks like @AdamBrodzinski screenshot.

?????

**Comment by AdamBrodzinski** [comment]
@fokkerone i'm not sure what commit you started with... what did you take out, the while loop? If so do you have the file `webpack/assets/server.bundlejs` in the webpack folder?

If you have time could you try out this [this fork](https://github.com/AdamBrodzinski/meteor-webpack-react/tree/new-structure) that's in this PR https://github.com/jedwards1211/meteor-webpack-react/pull/15 ?  I'm just curious to see if it has the same issues as well.

**Comment by jedwards1211** [comment]
@fokkerone sorry to hear that, did it print some error in the console when the script tried to run node-inspector?
I understand `meteor debug` is the usual way to run node-inspector, but it seems to have an old version of node-inspector that didn't have a Profiler tab.  The way I had done it in my script, on my machine at least it was able to launch a newer version of node-inspector that has a profiler.

Also when did you last pull?  Yesterday afternoon I fixed a race condition where Meteor could start all the way up before the server bundle got built (I put while loops to wait until that file is created in new version of the scripts).  I think that might be what was causing your problem.  I remember the one time Meteor finished starting first on my machine, it never seemed to pick up the server bundle once it was created.

**Comment by grigio** [comment]
I confirm this bug now.. :( Meteor itself isn't 100%
Maybe webpack is watching too many files?

**Comment by fokkerone** [comment]
@grigio Nope, the problem just depends on the npm run startscripts , @jedwards1211 also in current version. 
If you remove the meteor call from bash script and call it from a second Terminal everything looks good. 
Starting the Webpack+Meteor from a Node Script with forever/spawn is also fine and might be the solution. 

@jedwards1211 The node-inspector throws a lot of errors in Chrome and i am not able to bring it up.
```javascript
Your Node version (v0.10.36) has a partial support of profiler.
The stack frames tree doesn't show all stack frames due to low sampling rate.
The profiling data is incomplete and may show misleading results.
Update Node to v0.11.13 or newer to get full support.
```
i´m running 0.12.7 on nvm, so meteor is still using an own node version in 1.x.x ? 

```javascript
Error: Cannot find module '/Users/thisplay/.npm-packages/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.5.2/node-v11-darwin-x64/debug.node'
```
same as above. inspector choose wrong v8 debugger

**Comment by jedwards1211** [comment]
Yes, Meteor picks out its own node version, for better or worse.  I happen to be running the same version of node (v0.10.36) outside of Meteor, so maybe that's why it worked for me (though I don't know why `meteor debug` won't give us a profiler).  My node-inspector version is v0.8.3.

I was still able to create a profile with those error messages, despite that it says the profiling data is incomplete.  Were you not even able to?  Perhaps it could at least shed some light on what's pegging the CPU.  But I'll see if I `nvm use 0.12.7` what happens...

**Comment by jedwards1211** [comment]
Nope, can't repro with 0.12.7 either.  I do of course see 100% CPU until Webpack finishes building, but that's to be expected.  Which node process (from `ps aux`) is the one pegging the CPU?

**Comment by fokkerone** [comment]
'''thisplay        12086 104,5  1,1  3309900 192428 s000  R+    3:52pm   0:36.05 /Users/thisplay/.meteor/packages/meteor-tool/.1.1.4.2l3p0l++os.osx.x86_64+web.browser+web.co
'''

**Comment by grigio** [comment]
@fokkerone for me, It fixed in this way:
```
rm -rf node_modules
npm install -g webpack-dev-server webpack
npm run dev 
```

**Comment by jedwards1211** [comment]
Hmmm.  We could try this:
In `webpack/scripts/dev.sh`, change `sleep 1` to `sleep 60` or long enough that you're sure it won't start meteor until everything else is done.
If that works, then it means starting meteor from the script isn't the problem, just that it's being started while things are building.

**Comment by firegoby** [comment]
I'm having exact same issue on Retina MBP too, 106% CPU usage (constant) from node.

I edited `webpack/scripts/dev.sh` to `sleep 60` and re-ran, problem remains unfortunately.

**Comment by fokkerone** [comment]
okay,

which version of npm you @firegoby + @jedwards1211 are using?
running  ./webpack/scripts/dev.sh from shell works. running npm run dev sucks
i am on ```$ npm -v 2.13.4 ```

**Comment by firegoby** [comment]
`npm --version` gives me `2.11.2`

Can also confirm *definitely* a problem in dev.sh - I've commented out lines #11-15 and moved the meteor start lines #17-20 to their own shell script and start both independently from command line and everything works fine, no CPU issue

**Comment by fokkerone** [comment]
@firegoby did you run the second script from npm or directly from shell?

**Comment by firegoby** [comment]
ran both directly from shell -- from project root `./webpack/scripts/dev.sh` and in another tmux window, also from project root `./webpack/scripts/meteor-dev.sh` (the shell script where I moved the meteor stuff)

**Comment by firegoby** [comment]
personally I prefer having the two processes running in separate windows/tabs, so I'll probably keep it this way, but yeah, the issue is definitely in this general area (`dev.sh` and/or `npm run` invocation)

**Comment by fokkerone** [comment]
please add this to package.json 
```
  "scripts": {
    "start": "webpack/scripts/meteor-dev.sh",

..
```
ran it with npm start

**Comment by firegoby** [comment]
wow! ok, running via NPM with the above `npm run start` alias causes a steady 174% CPU usage - so looks like we have our suspect...

**Comment by fokkerone** [comment]
https://github.com/meteor/meteor/issues/4314

**Comment by firegoby** [comment]
ah nice find @fokkerone Thanks! - well that explains it then. I'll be starting from shell instead. Probably best just add a note to the README, other than that not sure what can be done to fix this on a local (non-core) level.

**Comment by AdamBrodzinski** [comment]
Ahhh great work! I wonder why it wasn't doing that for me. Does it take awhile to get up there? 

I'm nuking my npm/node today but here's my current setup: 

```
npm -v
2.13.4
node -v
v0.10.32
```

**Comment by firegoby** [comment]
the CPU usage? no delay, jumps straight up and holds there steady...

**Comment by jedwards1211** [comment]
Aha, thanks a bunch @fokkerone for finding that!  So I will move the scripts into the root folder then, so that everyone can easily run them without npm.  Later I'll make scripts that only start the Webpack instances for those who want to use them that way.

**Comment by jedwards1211** [comment]
Programming these days is like kids think chemistry works...mix any random things and it might blow up!

**Comment by jedwards1211** [comment]
Okay, I moved the scripts into the root folder: https://github.com/jedwards1211/meteor-webpack-react/commit/a85937448b5cec31179520eb0c333bb52b95aeba
See the updated README if you have trouble finding them.  Let me know if you run into problems running these scripts

**Comment by fokkerone** [comment]
here ii my solution for only one Terminal Window:
1) a start.js
```javascript
#!/usr/bin/env node

var spawn = require('child_process').spawn
var exec = require('child_process').exec
var appDir = process.cwd();
//
// // process.chdir(appDir + '/webpack.scripts');
spawn('./webpack/scripts/dev.sh', [], { stdio: 'inherit' });
process.chdir(appDir + '/meteor_core');
var m = spawn('meteor', []);

m.stdout.on('data', function (data) {
  console.log(''+data);
});
```
2) remove the meteor call from dev.sh
3) add this to the package.json

  "scripts": {
    "start": "node start.js",

call npm start
up an running
... the chemicals mix but don´t shake!!!

**Comment by grigio** [comment]
@fokkerone is possible to prepend `w:` and `m:` to the webpack and meteor output?

**Comment by ShockiTV** [comment]
I think the old ( using by Meteor internally ) and new ( installed by devs locally ) Node streams cooperation is kinda borked.
Simple nvm-ing to 0.10.40 node version bring both on same level and fixed CPU issues.
Have fun and thanks for all the fishes.

**Comment by ShockiTV** [comment]
As we need to run also chimp and I would prefer still use current npm by default and not switch by hand so I prepared little wrapper for brew installed nvm on my OSX.

Roberts-MacBook-Pro:~ shock$ cat .bash_profile 
```
export NVM_DIR=~/.nvm
. /usr/local/opt/nvm/nvm.sh
alias npm="~/.npm_wrapper.sh"
```

Roberts-MacBook-Pro:~ shock$ cat .npm_wrapper.sh 
```
#!/bin/bash

readonly METEOR_NODE_VERSION="0.10.40"

# source nvm script installed by brew
. /usr/local/opt/nvm/nvm.sh

if [[ "$1" == "run" && ( "$2" == "start" || "$2" == "testEnv" ) ]]
then
  echo "Using npm for $METEOR_NODE_VERSION"
  nodePath=$(nvm which $METEOR_NODE_VERSION)
  npmPath=$(echo $nodePath | sed 's/node$/npm/')
  exec "$npmPath" $@
else
  # exec with current node
  nodePath=$(nvm which current)
  npmPath=$(echo $nodePath | sed 's/node$/npm/')
  exec "$npmPath" $@
fi

echo "Something went horribly wrong in npm_wrapper.sh"
exit 1
```
Bye
